### PyTorch Tensors
#### LINK: https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html

In [1]:
import torch
import math

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[-1.1404e-06,  4.5646e-41, -1.1404e-06,  4.5646e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [4]:
# common cases for initialization
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


#### Random Tensors and Seeding

In [5]:
# we use manual seeding when we want reproducible values
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


#### Tensor shapes

In [9]:
# often, when working with tensors, we will want them to be the same dimension. 
# Enter the torch.*_like() methods

x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

torch.manual_seed(1729)
random_like_x = torch.rand_like(x)
print(random_like_x.shape)
print(random_like_x)

torch.Size([2, 2, 3])
tensor([[[-3.7888e+29,  3.0872e-41,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00]],

        [[ 1.0000e+00,  1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[-1.1403e-06,  4.5646e-41, -1.1403e-06],
         [ 4.5646e-41,  0.0000e+00,  0.0000e+00]],

        [[ 1.4013e-45,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.3126, 0.3791, 0.3087],
         [0.0736, 0.4216, 0.0691]],

        [[0.2332, 0.4047, 0.2162],
         [0.9927, 0.4128, 0.5938]]])


In [13]:
# create a tensor with data directly from a PyTorch collection
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


#### Tensor Data Types

In [16]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.3283,  0.2118, 18.4972],
        [ 9.8370,  3.8937, 16.1945]], dtype=torch.float64)
tensor([[18,  0, 18],
        [ 9,  3, 16]], dtype=torch.int32)


#### Math & Logic with PyTorch Tensors 

In [18]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [20]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [22]:
# tensors must be of the same shape
a = torch.rand(2, 3)
b = torch.rand(3, 2)

# print(a * b)

#### In Brief: Tensor Broadcasting

In [23]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.1332, 0.0023, 0.4945, 0.3857],
        [0.9883, 0.4762, 0.7242, 0.0776]])
tensor([[0.2663, 0.0045, 0.9890, 0.7715],
        [1.9767, 0.9524, 1.4484, 0.1553]])


In [29]:
# Broadcasting rules examples
a = torch.ones(4, 3, 2)

b = a * torch.rand(  3, 2) # 3rd and 2nd dims are identical to a, but dim1 is absent
print(b.shape)
print(b)

c = a * torch.rand(  3, 1) # 3rd dimension = 1, 2nd dimension is identical to a, dim1 is absent
print(c.shape)
print(c)

d = a * torch.rand(  1, 2) # 3rd dimension is identical to a, 2nd dimension is 1, 1st dimension is absent
print(d.shape)
print(d)

torch.Size([4, 3, 2])
tensor([[[0.6339, 0.3208],
         [0.4323, 0.1811],
         [0.6962, 0.8073]],

        [[0.6339, 0.3208],
         [0.4323, 0.1811],
         [0.6962, 0.8073]],

        [[0.6339, 0.3208],
         [0.4323, 0.1811],
         [0.6962, 0.8073]],

        [[0.6339, 0.3208],
         [0.4323, 0.1811],
         [0.6962, 0.8073]]])
torch.Size([4, 3, 2])
tensor([[[0.2125, 0.2125],
         [0.3977, 0.3977],
         [0.3132, 0.3132]],

        [[0.2125, 0.2125],
         [0.3977, 0.3977],
         [0.3132, 0.3132]],

        [[0.2125, 0.2125],
         [0.3977, 0.3977],
         [0.3132, 0.3132]],

        [[0.2125, 0.2125],
         [0.3977, 0.3977],
         [0.3132, 0.3132]]])
torch.Size([4, 3, 2])
tensor([[[0.6331, 0.8222],
         [0.6331, 0.8222],
         [0.6331, 0.8222]],

        [[0.6331, 0.8222],
         [0.6331, 0.8222],
         [0.6331, 0.8222]],

        [[0.6331, 0.8222],
         [0.6331, 0.8222],
         [0.6331, 0.8222]],

        [[0.6331, 0.8

#### More Math with Tensors

In [33]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print(a)
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[-0.4908,  0.8738,  0.4975,  0.8212],
        [ 0.7883,  0.5985, -0.8892,  0.1552]])
Common functions:
tensor([[0.4908, 0.8738, 0.4975, 0.8212],
        [0.7883, 0.5985, 0.8892, 0.1552]])
tensor([[-0., 1., 1., 1.],
        [1., 1., -0., 1.]])
tensor([[-1.,  0.,  0.,  0.],
        [ 0.,  0., -1.,  0.]])
tensor([[-0.4908,  0.5000,  0.4975,  0.5000],
        [ 0.5000,  0.5000, -0.5000,  0.1552]])


In [34]:
# trigonometric functions and their inverses
print('\nSine and arcinse:')
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print(angles)
sines = torch.sin(angles)
print(sines)
inverses = torch.asin(sines)
print(inverses)


Sine and arcinse:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [35]:
# bitwise operations
print('Bitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

Bitwise XOR:
tensor([3, 2, 1])


In [36]:
# comparisons:
print("\nBroadcasted, element-wise equality comparison:")
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2) # many comparison ops support broadcasting
print(torch.eq(d, e))


Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])


In [40]:
# reductions
print("\nReduction ops:")
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements


Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [42]:
# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition


Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.2038, 0.2881],
        [0.2677, 0.3067]])
tensor([[0.6115, 0.8644],
        [0.8031, 0.9200]])
torch.return_types.svd(
U=tensor([[-0.6548, -0.7558],
        [-0.7558,  0.6548]]),
S=tensor([1.6143, 0.0816]),
V=tensor([[-0.6241,  0.7814],
        [-0.7814, -0.6241]]))


#### Altering Tensors in Place

In [46]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))
print(a)


b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b)) # alters the actual tensor
print(b)

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [47]:
# similarly but for arithmetic functions
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print("Before:")
print(a)
print(b)

print("\nAfter adding:")
print(a.add_(b))
print(a)
print(b)
print("\nAfter multiplying:")
print(b.mul_(a))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.6961, 0.5406],
        [0.5028, 0.0389]])

After adding:
tensor([[1.6961, 1.5406],
        [1.5028, 1.0389]])
tensor([[1.6961, 1.5406],
        [1.5028, 1.0389]])
tensor([[0.6961, 0.5406],
        [0.5028, 0.0389]])

After multiplying:
tensor([[1.1806, 0.8329],
        [0.7555, 0.0404]])
tensor([[1.1806, 0.8329],
        [0.7555, 0.0404]])


In [58]:
# There is another option for placing the result of a computation in an existing, allocated tensor. 
# Many of the methods and functions we’ve seen so far - including creation methods! - have an out argument 
# that lets you specify a tensor to receive the output. 
# If the out tensor is the correct shape and dtype, this can happen without a new memory allocation:

a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c), old_id    # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c), old_id    # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[1.2903, 0.7164],
        [0.3355, 0.1955]])
tensor([[0.3966, 0.7251],
        [0.4472, 0.5901]])


#### Copying Tensors 

In [59]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)       # ...and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])


In [61]:
# if we want separate ones, we use clone() method
a = torch.ones(2, 3)
b = a.clone()

assert b is not a
print(torch.eq(a, b))

a[0][1] = 561
print(b)

# NOTE: If your source tensor has autograd, enabled then so will the clone.

tensor([[True, True, True],
        [True, True, True]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [62]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone() # turning autograd off for the clone
print(c) 

print(a)

tensor([[0.1451, 0.1924],
        [0.7354, 0.6377]], requires_grad=True)
tensor([[0.1451, 0.1924],
        [0.7354, 0.6377]], grad_fn=<CloneBackward0>)
tensor([[0.1451, 0.1924],
        [0.7354, 0.6377]])
tensor([[0.1451, 0.1924],
        [0.7354, 0.6377]], requires_grad=True)


#### Moving to GPU

In [63]:
if torch.cuda.is_available():
    print("We have a GPU!")
else:
    print("Sorry, CPU only!")

We have a GPU!


In [64]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device="cuda")
    print(gpu_rand)
else:
    print("Sorry, CPU only!")

tensor([[0.3344, 0.2640],
        [0.2119, 0.0582]], device='cuda:0')


In [65]:
torch.cuda.device_count()

1

In [67]:
# better practice
if torch.cuda.is_available():
    my_device = torch.device("cuda")
else:
    my_device = torch.device("cpu")

print("Device:{}".format(my_device))
x = torch.rand(2, 2, device=my_device)
print(x)

Device:cuda
tensor([[0.0024, 0.6778],
        [0.2441, 0.6812]], device='cuda:0')


In [68]:
# moving a tensor to another device
y = torch.rand(2, 2) # created on the CPU
y = y.to(my_device) # moved to GPU

In [69]:
# if we want to do tensor computations, all the tensors must be on the same device
x = torch.rand(2, 2)
y = torch.rand(2, 2, device="gpu")

z = x + y # exception will be thrown

RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, ort, mps, xla, lazy, vulkan, meta, hpu, privateuseone device type at start of device string: gpu

#### Manipulating Tensor Shapes

In [70]:
# Changing the Number of Dimensions
a = torch.rand(3, 266, 266)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)
# The unsqueeze() method adds a dimension of extent 1. unsqueeze(0) adds it as a new zeroth dimension 

torch.Size([3, 266, 266])
torch.Size([1, 3, 266, 266])


In [75]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.4385]]]]])


In [80]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

e = torch.rand(1, 2, 2)
print(e.shape)

f = e.squeeze(0)
print(f.shape)

torch.Size([1, 20])
tensor([[0.0476, 0.5193, 0.9329, 0.1729, 0.3628, 0.6455, 0.5140, 0.8448, 0.1976,
         0.8465, 0.3017, 0.1697, 0.7425, 0.2339, 0.7327, 0.1535, 0.5121, 0.0494,
         0.4677, 0.4314]])
torch.Size([20])
tensor([0.0476, 0.5193, 0.9329, 0.1729, 0.3628, 0.6455, 0.5140, 0.8448, 0.1976,
        0.8465, 0.3017, 0.1697, 0.7425, 0.2339, 0.7327, 0.1535, 0.5121, 0.0494,
        0.4677, 0.4314])
torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([1, 2, 2])
torch.Size([2, 2])


In [87]:
a = torch.ones(4, 3, 2)
print(a)
b = torch.rand(3, 1)
print(b)
c = a * b # 3rd dim = 1, 2nd dim identical to a, 1st dim missing
print(c)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[0.3317],
        [0.5148],
        [0.7466]])
tensor([[[0.3317, 0.3317],
         [0.5148, 0.5148],
         [0.7466, 0.7466]],

        [[0.3317, 0.3317],
         [0.5148, 0.5148],
         [0.7466, 0.7466]],

        [[0.3317, 0.3317],
         [0.5148, 0.5148],
         [0.7466, 0.7466]],

        [[0.3317, 0.3317],
         [0.5148, 0.5148],
         [0.7466, 0.7466]]])


In [90]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

torch.Size([3, 1])
tensor([[[0.2859, 0.2859],
         [0.7983, 0.7983],
         [0.0026, 0.0026]],

        [[0.2859, 0.2859],
         [0.7983, 0.7983],
         [0.0026, 0.0026]],

        [[0.2859, 0.2859],
         [0.7983, 0.7983],
         [0.0026, 0.0026]],

        [[0.2859, 0.2859],
         [0.7983, 0.7983],
         [0.0026, 0.0026]]])


In [94]:
batch_me = torch.rand(3, 266, 266)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 266, 266])
torch.Size([1, 3, 266, 266])


In [96]:
# changing the shape of a tensor more radically
# for example when interfacing a convolutional layer (features x width x height) with a linear layer (1 dim)
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


#### NumPy Bridge

In [97]:
import numpy as np

In [98]:
numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [99]:
# converting the other way
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.7616, 0.0350, 0.1430],
        [0.3852, 0.5181, 0.5571]])
[[0.76162845 0.03503084 0.143022  ]
 [0.3852452  0.51806194 0.55711746]]


In [102]:
# the objects use the same underlying memory, meaning changing one also changes the other
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 18
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.76162845  0.03503084  0.143022  ]
 [ 0.3852452  18.          0.55711746]]
